### ISSUE TITLE
JSON 포멧 snake_case 로 작성

### ISSUE THREAD

**Issue by namenu** [ridibooks/viewer-notification#1]
현재 요청/응답에 사용되는 JSON의 프로퍼티 이름은 camelCase로 되어있습니다.

아직 RIDI Style Guide에 JSON과 관련된 내용은 없지만, GitHub, Google, Facebook, Twitter 등 많은 곳에서 snake_case 형태를 사용하고 있어서 우리 역시 이를 따르려고 합니다.

(RIDI RESTful API Guide 는 조만간 작성하여 전사적으로 공유될 수 있도록 하겠습니다.)

**Comment by kyungmi** [comment]
snake_case를 사용하게 될 경우에 API 요청을 할 때마다 내부적으로 변환 작업이 일어나야 해서 비용이 들어가게 되는데요. 크게 상관 없을까요?

**Comment by namenu** [comment]
저는 여기서 참고했습니다. (구글은 서비스마다 다른가 보네요..)
http://zalando.github.io/restful-api-guidelines/json-guidelines/JsonGuidelines.html

지금 JavaScript 는 변수에 camelCase 를 쓰고 있고, PHP 는 snake_case 를 사용하고 있는데요.
때문에 무엇으로 정하더라도 어느 한쪽은 변환을 해야하므로, 변환 비용은 어쩔 수 없다고 생각합니다.

우선.. JSON 스타일을 최대한 빨리 결정지어 보겠습니다!

**Comment by kyungmi** [comment]
넵 저도 다른 API서비스들을 찾아봤는데, 대부분 snake_case를 사용하고 있네요.
그리고 더불어서 url(resource 이름이 복합어일 경우)이나 query string(이름, 값)에 대한 가이드도 필요할 것 같습니다. 지금 이 코드 내에서는 모두 camelCase를 사용하고 있는데 snake_case로 변경하는 것이 좋을 것 같기도 하고요.
우선 response json에 대해서 snake_case로 변환 작업 진행하겠습니다.

**Comment by namenu** [comment]
네, 참고하겠습니다.

현재 (암묵적으로) URL에는 ``-```를 사용하고 있는데, ```_```보다 SEO에 적합하다는 자료를 보았기 때문이고요,
Query string 에는 아직 특별한 기준이 없습니다만, 정한다면 propery 와 동일하게 정하는 것이 좋겠습니다.

**Comment by kyungmi** [comment]
답변 감사합니다 참고할게요~

**Comment by kyungmi** [comment]
@namenu 
작업 완료했습니다.
추가로 단수명을 가진 배열 타입의 프로퍼티가 있어서 복수형으로 바꿨어요.

이번에 작업을 해보니까 서버-클라이언트 각각 2번의 변환작업이 있어야 해서 총 4번의 변환이 일어나는데요. 현재는 object(또는 array)를 recursive하게 돌면서 처리하고 있는데, 나중에 이 과정을(문자열로 치환한 후에 regex를 사용한다던지 해서) 좀 더 간결하게 개선해야 할 것 같습니다.
